### ISSUE TITLE
Scrolling issues

### ISSUE THREAD

**Issue by 2Ratz** [ChernyshovYuriy/OpenRadio#11]
When I scroll down for example the Dutch country, halfway it coms to "Z" and then it start over with "T". See screenshot, ignore the "W" I don't know why is is there :-)

When at the end of scrolling "No data recieved" appears" it does not play new channels when clicked but after buffering it keeps playing the current channel which was played.

When scrolled down in the country Belgium I got the "NO DATA RECIEVED" message halfway when going va "r" to "s".

![Screenshot_20230907_145657_Open Radio](https://github.com/ChernyshovYuriy/OpenRadio/assets/143018825/43f092f6-7e66-4246-9d52-a3ad6321f409)
![Screenshot_20230907_145430_Open Radio](https://github.com/ChernyshovYuriy/OpenRadio/assets/143018825/f79fd402-ea51-4525-b213-9d541b9fe1d5)
![Screenshot_20230907_145616_Open Radio](https://github.com/ChernyshovYuriy/OpenRadio/assets/143018825/3ed819c3-59f7-4a76-8982-e80dd3c3c242)

**Comment by ChernyshovYuriy** [comment]
Yeah, this is fixed and submitted to Google for review yesterday.
This is also a duplication of https://github.com/ChernyshovYuriy/OpenRadio/issues/5.

**Comment by ChernyshovYuriy** [comment]
yes, that should be fixed as separate issue (tracked here), please wait for the release.

**Comment by 2Ratz** [comment]
I just got the update. Scrolling is smooth, no strange behaviour starting
halfway again with previous letters but.... when I reach the end it does
not play the last channels. So there is a cosmic update with "no data
recieved" which is gone but the same behaviour with not playing the last
channels.

Op do 7 sep 2023 om 15:36 schreef Yurii Chernyshov ***@***.***

**Comment by 2Ratz** [comment]
Do you prefer a new ticket for this issue?

Op do 7 sep 2023 om 18:32 schreef Rick ***@***.***>:

**Comment by ChernyshovYuriy** [comment]
Yes, that will be appropriate.

**Comment by ChernyshovYuriy** [comment]
"No data received" is fixed.
