### ISSUE TITLE
"No data recieved" pops up.

### ISSUE THREAD

**Issue by 2Ratz** [ChernyshovYuriy/OpenRadio#14]
Hello, 

"No data recieved" pops up while just listening to a station, the app is still functioning and plays other channels when switched to another channel. The icon play/pause is spinning but that disappears when you switch to another channe;.

I cannot reproduce it but I mentioned it before in another issue .

![Screenshot_20230910_110543_Open Radio(1)](https://github.com/ChernyshovYuriy/OpenRadio/assets/143018825/e6149662-5df8-4559-a107-48334cde215d)

**Comment by ChernyshovYuriy** [comment]
Can you try on the latest version, please?

**Comment by 2Ratz** [comment]
Just tested for two hours but I can no longer reproduce it. I did have one pop-up when I turned on the phone with "no data received" but that lasted less than a fraction of a second. So that is very nice. I sent a log at the same time as this response.

Different topic, I miss the play button. I think this is very confusing for new users and for me too at times.

**Comment by ChernyshovYuriy** [comment]
Play Button never served its purpose well, it was located closed to Favorite and the top rectangular with Now Playing Station is a button itself, so user can tap on Radio Station to toggle the state. It might be a better way to indicate that by the User Interface design, but I dont know how to do that.
