### ISSUE TITLE
Stream does not recover with mobile signal with Android Auto

### ISSUE THREAD

**Issue by Jerther** [ChernyshovYuriy/OpenRadio#21]
Hi!

Nice work on this app! Thank you :)

Here are, to the best of my knowledge, the steps to reproduce the issue I'm having:
- Make sure the cell phone is on a mobile network, not wifi. (may not matter though. Not sure.)
- Link the cell phone to android auto (may not matter, not sure.)
- Select a radio station and click Play.
- While the station is streaming, have the network signal drop to inexistant.
- The stream of course stops, and the app shows it is trying to recover
- Have the mobile network signal come back up
--> The stream never recovers. Pressing pause then play again does not fix it.

Here's a workaround:
- While the stream is trying to recover, select another station. This one plays fine. Then select the previous station, and it is fine now.

**Comment by ChernyshovYuriy** [comment]
Thank you for report.
I will look at it next week.

**Comment by Jerther** [comment]
I've had many rides with spotty 5G connections last week and apprently the problem does not happen anymore. Not sure what changed, if anything?

**Comment by ChernyshovYuriy** [comment]
Nothing changed from Open Radio side, maybe radio stream parameters changed?

**Comment by Jerther** [comment]
Not sure... Well we can close this for now I think.
