### ISSUE TITLE
Sign.properties missing

### ISSUE THREAD

**Issue by wandersiemers** [ChernyshovYuriy/OpenRadio#22]
Hi!

I'm trying to build this app myself for research purposes, however I run into the issue that `sign.gradle` looks for `sign.properties` which it cannot find. How do I set this up?

Thanks in advance!

**Comment by ChernyshovYuriy** [comment]
Hello.
This is the file that contains private information related to sign data used to publish the application.
For obvious reasons - it is not included.
You have two options - either include your own file or exclude this logic altogether from gradle.
I am not going to help with either way, this is specific action each engineer should take care of.
