### ISSUE TITLE
Please make .apk available on fdroid.org or on github?

### ISSUE THREAD

**Issue by timvak** [ChernyshovYuriy/OpenRadio#24]
Hi Yuriy,

I'm really enjoying the radio app, it's the best I've user so far.

I'm migrating to GrapheneOS so don't want to use Google play anymore. Can you please release here or on fdroid.org? Then i can keep enjoying your work 😉

Thanks in advance.
Best Regards

**Comment by ChernyshovYuriy** [comment]
Hi, it is not hard to provide with APKs. I might need to check the code to exclude Google features, such as Firebase, Drive, etc ...

**Comment by timvak** [comment]
If you could do that, it would be most appreciated!
Let me know where it's gonna be released when you're able.

**Comment by ChernyshovYuriy** [comment]
Btw, I do have some old versions here:
https://github.com/ChernyshovYuriy/OpenRadio/tree/master/app/store
I assume you do need mobile version only, not TV, no Automotive, right?
I will upload latest mobile as well and as is, with Google services, let me know how it works and whether I need to remove Google libraries from it.

**Comment by timvak** [comment]
If you could release a version without google services, that would be great. 
I use https://github.com/ImranR98/Obtainium/ to manage my apps and stay updated. but somehow when I try to add your repo I get the error could not find suitable release. Any idea why? Or should I contact Imran for that?

**Comment by ChernyshovYuriy** [comment]
Sorry, but I don't intend to explore systems like Obtanium, F-Droid, and others. The directory I provided contains pure 'apk' files that can be installed on any Android system. I don't believe Google Services will cause installation issues, but they might lead to runtime problems. If you encounter any issues, please file a ticket addressing your specific use case. With that being said, I'm going to close this ticket.

**Comment by timvak** [comment]
I understand. Thank you for the help and making the .apk available. If you can send a Lightning invoice, I'll give you a coffee 😉
