### ISSUE TITLE
The previous button for HLS-based channels doesn't work correctly

### ISSUE THREAD

**Issue by R4ssez** [ChernyshovYuriy/OpenRadio#26]
https://github.com/google/ExoPlayer/issues/7222 Same problem as this. Only affects on HLS streams.

**Comment by R4ssev** [comment]
https://github.com/google/ExoPlayer/issues/7222

**Comment by ChernyshovYuriy** [comment]
Hello.
If Google guys closed the ticket, I am not sure what is expected from me :-) Open Radio simple uses Exo Player as is, no changes or modifications.
