### ISSUE TITLE
[Feature Request] Possibly to sort favorites.

### ISSUE THREAD

**Issue by Dtrieb** [ChernyshovYuriy/OpenRadio#29]
Give the user the possibility to sort the favorite stations in the list.

**Comment by ChernyshovYuriy** [comment]
It does work, not ideal, I would prefer different technique for Mobile but I found this common between Mobile and TV.
![Screenshot_20231030_172408](https://github.com/ChernyshovYuriy/OpenRadio/assets/931955/23ec0bc0-a3bd-47e0-a0aa-f17923a5a6da)
![Screenshot_20231030_172423](https://github.com/ChernyshovYuriy/OpenRadio/assets/931955/a05f9f38-b45d-403e-b039-d684c79649a9)
