### ISSUE TITLE
Suggestion: Open discussions category/feature on this repository

### ISSUE THREAD

**Issue by goliv04053** [ChernyshovYuriy/OpenRadio#30]
Good morning. I don't know if this is to ask here but I was going to ask about how Open Radio analyses country codes. But I don't know if this is to ask here on the Issues category.

**Comment by ChernyshovYuriy** [comment]
Hello. Ask any question, any category - I will change titles if needed :-)

As to the Country Code, it is provided by the database. For example, CBC:
https://www.radio-browser.info/history/147a830e-fbc3-4260-9504-6dcc62530923
Or, here, if you select just Canada and click search:
https://jcorporation.github.io/webradiodb

I have a map of codes to names, where i try to correct any issues introduced by users who added radio station and provided ambiguous name: USA, United States, America, etc ... all this is USA obviously.

And country code is defined here:
https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3

**Comment by goliv04053** [comment]
About the country codes, i was having some problems adding a radio from North Korea (DPRK) and for some reason it wasn't detecting in the OpenRadio app (The database I am adding radios is webradiodb from jcorporation)

Not related to the previous topic but In the title I also meant about https://docs.github.com/en/discussions
It's a feature on Github and i think it would be useful.

**Comment by goliv04053** [comment]
I gave a look on the code and created a issue to modify the country to "Korea, Democratic People's Republic of".
Don't know if it will work. I have to wait to the radio data go online on the website of webradiodb.

**Comment by ChernyshovYuriy** [comment]
Ok, i see it is there, will take a look at Open Radio code, thanks!

![Screenshot from 2023-11-03 11-49-47](https://github.com/ChernyshovYuriy/OpenRadio/assets/931955/3befbc3b-2783-46cc-9a80-8bc7c3558ad4)

**Comment by goliv04053** [comment]
When I said code, i meant OpenRadio code. I gave a look here to change the country there. But I still have to wait to see if it's going to work here

**Comment by goliv04053** [comment]
Nope. Not working.

**Comment by goliv04053** [comment]
@ChernyshovYuriy any news?

**Comment by ChernyshovYuriy** [comment]
North Korea fixed for Web Radio and change is released.
Radio Browser don't have such country in its list, I would suggest to contact the owner at https://www.radio-browser.info

**Comment by goliv04053** [comment]
Okay. Gonna give a look on Radio-Browser too
