### ISSUE TITLE
Several issues after update.

### ISSUE THREAD

**Issue by 2Ratz** [ChernyshovYuriy/OpenRadio#5]
Hi, this is an annoying update, I'm sorry I did it, I hope you can restore some things, especially the playback of some channels as I already reported to you (Kink, Zeilsteen etc).

First after the update I uninstalled and reinstalled the app because it no longer plays some of my favorite channels and then gives the message "buffering...". It doesn't matter if the source is the "radio browser" or the "web radio". Unfortunately this makes no difference, note that the channels still worked on the old version.

Secondly, if I scroll all the way down in a country because I want to go to "Zeilsteen", for example, the message "No data received" appears in the middle, after which nothing is played anymore and you have to close the app to see the channels that do work again. to be able to play.

Third, when the app starts up, there is a circle under the heart that keeps spinning as if something needs to be loaded. I have disabled the options "Play last know.." and "Resume playback.." so it can't be that.

Gr Rick

**Comment by ChernyshovYuriy** [comment]
Hi, Yes, I noticed that, I do have crash reporting system in place.
The playback - I pushed fixes and wait for Google to verify and update.
I will fix the second and third issues later on.

**Comment by ChernyshovYuriy** [comment]
Updates finally available for Mobile at least - can you check?

**Comment by ChernyshovYuriy** [comment]
Ok, thats fine. Update fixed urgent crashes. Do you have a list of stations so I can check on my local environment?

**Comment by ChernyshovYuriy** [comment]
I got the reason. Too many things to redesign at once. Will try to solve it as soon as possible.

**Comment by 2Ratz** [comment]
Good to hear you find the problems. I look forward to the solutions. Take
your time :-)

Gr Rick

Op zo 27 aug 2023 om 05:12 schreef Yurii Chernyshov <
***@***.***>:

**Comment by ChernyshovYuriy** [comment]
Search should be fixed by latest update.

**Comment by 2Ratz** [comment]
Checked and yes it does and very fast and with more results!! So much
better then before the big update. Thankyou!

Op ma 28 aug 2023 om 01:29 schreef Yurii Chernyshov <
***@***.***>:

**Comment by 2Ratz** [comment]
Channels are playing! Very thankfull for that!

Remains the "No Data Recieved" at the end of a list/landlist.

Gr Rick

Op ma 28 aug. 2023 09:37 schreef Rick ***@***.***>:

**Comment by ChernyshovYuriy** [comment]
Can we close this ticket?

**Comment by 2Ratz** [comment]
yes

Op do 7 sep 2023 om 18:54 schreef Yurii Chernyshov ***@***.***

**Comment by 2Ratz** [comment]
Also compliment for the solutions, I'm very happy with them.

Op do 7 sep 2023 om 18:56 schreef Rick ***@***.***>:
