### ISSUE TITLE
AAOS artist and song titles missing

### ISSUE THREAD

**Issue by Raitsa** [ChernyshovYuriy/OpenRadio#6]
AAOS artist and song titles now missing after updating to 12.0

**Comment by ChernyshovYuriy** [comment]
AAOS - is android automotive, right?
I have some fixes around metadata but blocked by Google's review :-(

**Comment by Raitsa** [comment]
Yeah Android Automotive OS, got a Volvo C40 electric and noticed this today on that one.

Keep up the good work, best player ever.

**Comment by ChernyshovYuriy** [comment]
I did a major refactoring as Google moving towards [media3 library](https://android-developers.googleblog.com/2023/03/media3-is-ready-to-play.html).
Unfortunately, it caused some regression ... i keep my eye on it :-) if no updates coming it is because it stacked at Google's review.

**Comment by Raitsa** [comment]
Just updated half an hour ago in the car.
No luck, artist and song info (metadata) still missing in Android Automotive. 
(Updated but still shows 12.0, I was expecting to see maybe 12.1).

But something good to report after updating all systems today: 
Android phone all ok with metadata. 
Android TV all ok with metadata.

**Comment by ChernyshovYuriy** [comment]
Got it.

**Comment by ChernyshovYuriy** [comment]
Can you test the latest release?

**Comment by Raitsa** [comment]
Just updated and working, BIG thanks  :1st_place_medal:
